services:
  web:
    image: servisofts/repo
    build: .
    env_file:
      - config.properties
    ports:
      - ${PORT_REPO}:80
      - ${PORT_UPLOAD}:8080
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ${ROOT_FILE}:/repo
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
