#!/bin/bash

JSON commands new

JSON options new

JSON options put "-h" "_help"

_help() {
    JSON help_info new
    JSON help_info put "_help" "Muestra la ayuda."
    shelp commands options help_info "mkdir"
    exit 0
}

export_module commands options

if [ -z "$2" ]; then
    sconsole -e "Se requiere la direccion del archibo"
    exit 0
fi


dir_from=$2
# url="$REPO_PATH$dir"
name_from=$(basename $dir_from)
sconsole -g "name_from = $name_from"
# curl -o "./$name" $url

curl --request POST "$REPO_UPLOAD_PATH" \
    -F "$dir_from"="mkdir"

# lista=($(curl -s "$url" | grep 'href' | perl -nle 'm/.*?href="(.*)?".*/; print $1' | grep -v '\.\.'))
# # sconsole -g "${lista[*]}"
# for key in ${lista[@]}; do
#     name=${key%/}
#     # echo -e "$name=$url$key"
#     printf "$name\t\t"
#     # exit 0
# done
# echo ""
