#!/bin/bash

JSON commands new

JSON options new

JSON options put "-h" "_help"

_help() {
    JSON help_info new
    JSON help_info put "_help" "Muestra la ayuda."
    shelp commands options help_info "upload"
    exit 0
}

export_module commands options

if [ -z "$2" ]; then
    sconsole -e "Se requiere la direccion del archibo"
    exit 0
fi

if [ ! -f "$2" ]; then
    sconsole -e "Archivo no existe ( $2 )"
fi

if [ -z "$3" ]; then
    sconsole -e "Se requiere la direccion de destino"
    exit 0
fi

dir_from=$2
dir_to=$3
# url="$REPO_PATH$dir"
name_from=$(basename $dir_from)
name_to=$(basename $dir_to)


sconsole -g "name_from = $name_from"
sconsole -g "name_to = $name_to"

# curl -o "./$name" $url
path_final="/$name_from"

if [ ! -z "$name_to" ]; then
    path_final="$dir_to"
fi

echo "$path_final"
curl --request POST "$REPO_UPLOAD_PATH" \
    -F "$path_final"=@"$dir_from"

# lista=($(curl -s "$url" | grep 'href' | perl -nle 'm/.*?href="(.*)?".*/; print $1' | grep -v '\.\.'))
# # sconsole -g "${lista[*]}"
# for key in ${lista[@]}; do
#     name=${key%/}
#     # echo -e "$name=$url$key"
#     printf "$name\t\t"
#     # exit 0
# done
# echo ""
